spring.application.name=${APP_NAME:Busstation}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/busapp}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:parola123}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

